# Generated by Django 4.1.4 on 2023-01-11 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_todo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "задание", "verbose_name_plural": "задания"},
        ),
        migrations.AlterField(
            model_name="todo",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.project",
                verbose_name="Задание",
            ),
        ),
    ]
